name: Test Custom Action

on: [push]

jobs:
  welcome-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # THIS IS YOUR CUSTOM ACTION
      - name: Greet Bharath
        uses: KUMAR-REDDY-BAVANASI/hello-action@v1 # Points to the v1 tag we created
        with:
          person_name: 'Bharath' # This passes the input
